<?php
    $identData = $this->getPostidentVerificationData();
?>
<div id="customer_info_tabs_customer_edit_tab_view_content">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-customer-view">
                <?php echo $this->__('E-POSTIDENT verification data') ?>
            </h4>
        </div>
        <fieldset>   
          <?php if (is_array($identData) && array_key_exists('identData', $identData)): ?>
            <table id="box-left" cellspacing="15">
                <tbody>
                    <?php foreach ($identData['identData'] as $key => $value): ?>
                        <tr>
                            <td><strong><?php echo $this->__($this->escapeHtml($key)) . ":"; ?></strong></td>
                            <td><?php echo $this->escapeHtml($value); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
           <?php else: ?>
             <p> <?php echo $this->__('For this customer verification data doesnt exist.') ?> </p>
            <?php endif; ?>
        </fieldset>
    </div>
</div>