<script type="text/javascript">
    Translator.add('Only charakters a-z, A-Z, 0-9 are allowed.', '<?php echo Mage::helper('postident')->__('Only charakters a-z, A-Z, 0-9 are allowed.') ?>');
    Translator.add('Please Enter a valid Client-ID.', '<?php echo Mage::helper('postident')->__('Please Enter a valid Client-ID.') ?>');
    Translator.add('Check Connect Error: Message not found.', '<?php echo Mage::helper('postident')->__('Check Connect Error: Message not found.') ?>');
    Translator.add('Check Connect Error: Response is no JSON format.', '<?php echo Mage::helper('postident')->__('Check Connect Error: Response is no JSON format.') ?>');
    Translator.add('Check Connect request failed.', '<?php echo Mage::helper('postident')->__('Check Connect request failed.') ?>');
</script>